# Site settings
title:          Deepsight Study Blog
description:    "Minimal Jekyll theme for storytellers"
url:            "https://chesterhow.github.io"

# Author
author:
  name:         Chester How
  url:          https://chester.how
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post
  - jekyll-remote-theme

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

#remote theme
remote_theme: chesterhow/tale



